ccc:
  jwt:
    secret-key: nihaoccc
    ttl: 7200000
    token-name: token

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webproject
    username: root
    password: chenzhiqi585812
    driver-class-name: com.mysql.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: chenzhiqi585812
  rabbitmq:
    host: 192.168.6.102 # ?????IP
    port: 5672 # ??
    virtual-host: / # ????
    username: ccc # ???
    password: 123 # ??